# Generated by Django 4.2.23 on 2025-08-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('service_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('repository', models.CharField(blank=True, max_length=255)),
                ('config_data', models.JSONField(default=dict)),
                ('last_execution', models.DateTimeField(blank=True, null=True)),
                ('total_executions', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failure_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('execution_data', models.JSONField(default=dict)),
                ('service_metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['service_name', '-started_at'], name='dashboard_s_service_b83d1c_idx'), models.Index(fields=['service_type', '-started_at'], name='dashboard_s_service_a957b3_idx'), models.Index(fields=['status', '-started_at'], name='dashboard_s_status_890d8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExecutionQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.IntegerField(default=0)),
                ('estimated_duration', models.IntegerField(blank=True, null=True)),
                ('execution_id', models.CharField(blank=True, max_length=255, null=True)),
                ('operation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['priority', 'created_at'],
                'indexes': [models.Index(fields=['status', 'priority', 'created_at'], name='dashboard_e_status_8d8a1e_idx'), models.Index(fields=['service_name', '-created_at'], name='dashboard_e_service_5d4b9f_idx')],
            },
        ),
    ]
